<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class OllamaService
{
    public function enhance(array $idea): array
    {
        $prompt = <<<PROMPT
You are a senior software architect, capstone adviser, and technical writer.

The following recommendation was GENERATED by a RULE-BASED Decision Support System.

IMPORTANT RULES

- NEVER invent information.
- NEVER change the facts.
- NEVER change the recommendation itself.
- ONLY improve the wording.
- Remove duplicated words.
- Make the title professional.
- Make the description sound like a capstone proposal.
- Improve the objectives.
- Return ONLY valid JSON.
- Do NOT use markdown.
- Do NOT explain your answer.

JSON FORMAT

{
    "title":"",
    "description":"",
    "general_objective":"",
    "specific_objectives":[]
}

RULE-BASED RECOMMENDATION

Title:
{$idea['title']}

Description:
{$idea['description']}

General Objective:
{$idea['general_objective']}

Specific Objectives:

{$this->formatObjectives($idea['specific_objectives'])}

PROMPT;

        try {

            $response = Http::timeout(180)
                ->post(config('services.ollama.url').'/api/generate', [
                    'model' => config('services.ollama.model'),
                    'prompt' => $prompt,
                    'stream' => false,
                    'options' => [
                        'temperature' => 0.3,
                    ],
                ]);

            if ($response->failed()) {

                Log::error('Ollama request failed', [
                    'status' => $response->status(),
                    'body' => $response->body(),
                ]);

                return $idea;
            }

            $text = trim($response->json()['response'] ?? '');

            Log::info('OLLAMA RESPONSE', [
                'response' => $text,
            ]);

            // Remove markdown if present
            $text = preg_replace('/```json/i', '', $text);
            $text = preg_replace('/```/', '', $text);

            // Extract only JSON object
            if (preg_match('/\{.*\}/s', $text, $matches)) {
                $text = $matches[0];
            }

            $result = json_decode($text, true);

            if (! is_array($result)) {

                Log::warning('Invalid JSON returned by Ollama.', [
                    'response' => $text,
                ]);

                return $idea;
            }

            return [
                ...$idea,

                'title' => $result['title'] ?? $idea['title'],

                'description' => $result['description'] ?? $idea['description'],

                'general_objective' => $result['general_objective'] ?? $idea['general_objective'],

                'specific_objectives' => $result['specific_objectives'] ?? $idea['specific_objectives'],
            ];

        } catch (\Throwable $e) {

            Log::error('Ollama Exception', [
                'message' => $e->getMessage(),
            ]);

            return $idea;
        }
    }

    private function formatObjectives(array $objectives): string
    {
        return collect($objectives)
            ->map(fn ($objective) => "- {$objective}")
            ->implode("\n");
    }
}
