<?php

use App\Models\CategoryAssignment;
use App\Models\IdeaEvaluation;
use App\Models\SavedIdea;
use App\Models\User;
use Illuminate\Support\Str;

function createDssIdeaEvaluation(array $attributes = []): IdeaEvaluation
{
    return IdeaEvaluation::query()->create(array_merge([
        'idea_title' => 'Campus Request Tracking System',
        'category' => 'Facilities',
        'feasibility' => 4,
        'impact' => 5,
        'complexity' => 3,
        'innovation' => 4,
        'overall_score' => 4.2,
        'recommendation' => 'Highly Recommended',
    ], $attributes));
}

function savedIdeaPayload(array $attributes = []): array
{
    return array_merge([
        'title' => 'Campus Request Tracking System',
        'description' => 'A single place for students to track requests across campus offices.',
        'category' => 'Facilities',
    ], $attributes);
}

test('a student can save an existing dss idea', function (): void {
    $student = User::factory()->create();
    createDssIdeaEvaluation();

    $this->actingAs($student)
        ->post(route('idea.save'), savedIdeaPayload())
        ->assertSessionHasNoErrors()
        ->assertSessionHas('success');

    expect(SavedIdea::query()->where('user_id', $student->id)->count())->toBe(1);
});

test('a fabricated idea cannot be saved', function (): void {
    $student = User::factory()->create();

    $this->actingAs($student)
        ->from(route('discover'))
        ->post(route('idea.save'), savedIdeaPayload([
            'title' => 'Totally Invented Capstone System',
            'description' => 'This idea was never generated by the DSS for any category.',
        ]))
        ->assertSessionHasErrors('title');

    expect(SavedIdea::query()->count())->toBe(0);
});

test('an idea saved with a mismatched category cannot be saved', function (): void {
    $student = User::factory()->create();
    createDssIdeaEvaluation();

    $this->actingAs($student)
        ->from(route('discover'))
        ->post(route('idea.save'), savedIdeaPayload(['category' => 'Library']))
        ->assertSessionHasErrors('title');

    expect(SavedIdea::query()->count())->toBe(0);
});

test('saving the same idea twice does not create a second row', function (): void {
    $student = User::factory()->create();
    createDssIdeaEvaluation();

    $this->actingAs($student)
        ->post(route('idea.save'), savedIdeaPayload())
        ->assertSessionHas('success');

    $this->actingAs($student)
        ->post(route('idea.save'), savedIdeaPayload())
        ->assertSessionHasNoErrors()
        ->assertSessionHas('info');

    expect(SavedIdea::query()->where('user_id', $student->id)->count())->toBe(1);
});

test('a saved idea stores the dss evaluation it came from', function (): void {
    $student = User::factory()->create();
    $evaluation = createDssIdeaEvaluation();

    $this->actingAs($student)->post(route('idea.save'), savedIdeaPayload());

    $idea = SavedIdea::query()->where('user_id', $student->id)->firstOrFail();

    expect($idea->idea_evaluation_id)->toBe($evaluation->id)
        ->and($idea->ideaEvaluation->is($evaluation))->toBeTrue()
        ->and($idea->title)->toBe($evaluation->idea_title)
        ->and($idea->category)->toBe($evaluation->category);
});

test('the saved ideas page exposes the original opportunity link', function (): void {
    $student = User::factory()->create();
    $evaluation = createDssIdeaEvaluation();

    SavedIdea::query()->create([
        'user_id' => $student->id,
        'title' => $evaluation->idea_title,
        'description' => 'A single place for students to track requests across campus offices.',
        'category' => $evaluation->category,
        'idea_evaluation_id' => $evaluation->id,
    ]);

    $opportunityUrl = route('feedback.category', [
        'category' => $evaluation->category,
        'idea' => $evaluation->idea_title,
    ]).'#idea-'.Str::slug($evaluation->idea_title);

    $this->actingAs($student)
        ->get(route('user.ideas'))
        ->assertOk()
        ->assertSeeText('View original opportunity')
        ->assertSeeText($evaluation->idea_title)
        ->assertSee($opportunityUrl)
        ->assertSeeText('DSS evaluation:')
        ->assertSeeText($evaluation->recommendation);
});

test('saved ideas without an evaluation id still render the page', function (): void {
    $student = User::factory()->create();

    SavedIdea::query()->create([
        'user_id' => $student->id,
        'title' => 'Legacy Saved Idea',
        'description' => 'Saved before evaluations were linked to saved ideas.',
        'category' => 'Enrollment',
    ]);

    $this->actingAs($student)
        ->get(route('user.ideas'))
        ->assertOk()
        ->assertSeeText('Legacy Saved Idea')
        ->assertSeeText('View original opportunity')
        ->assertDontSeeText('DSS evaluation:');
});

test('the saved ideas page shows the responsible office for assigned categories', function (): void {
    $student = User::factory()->create();

    CategoryAssignment::query()->create([
        'category' => 'Enrollment',
        'office' => 'office_chief',
    ]);

    SavedIdea::query()->create([
        'user_id' => $student->id,
        'title' => 'Responsible Office Idea',
        'description' => 'Saved idea in a category that already has an assigned office.',
        'category' => 'Enrollment',
    ]);

    $this->actingAs($student)
        ->get(route('user.ideas'))
        ->assertOk()
        ->assertSeeText('Responsible office:')
        ->assertSeeText('Chief Administrative Office');
});
